name: escooter_notes_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  go_router: ^14.1.2
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.6
  http: ^1.1.0
  lottie: ^3.3.1
  jwt_decode: ^0.3.1
  provider: ^6.1.4
  logger: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  phone_input: ^1.0.0
  iconsax: ^0.0.8
  country_picker: ^2.0.26
  flutter_bloc: ^8.1.5
  rxdart: ^0.27.7
  flutter_dotenv: ^5.1.0
  pointycastle: ^3.9.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  equatable: ^2.0.0
  cached_network_image: ^3.3.1
  appwrite: ^15.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

    uses-material-design: true
    generate: true
    assets:
      - assets/images/
      - assets/icons/
      - assets/fonts/
      - assets/animations/

    fonts:
      - family: BebasNeue
        fonts:
          - asset: assets/fonts/BebasNeue-Regular.ttf
            weight: 800
